REVOKE ALL ON SCHEMA public FROM public;
GRANT CONNECT ON DATABASE eosmdbtwo TO public;
GRANT USAGE ON SCHEMA public TO public;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO public;

CREATE ROLE guest WITH LOGIN PASSWORD 'Test1234';

CREATE TABLE already_here (
    id_here INTEGER
);